name: task_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path: ^1.9.1
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  intl: ^0.20.2
  gap: ^3.0.1
  loading_animation_widget: ^1.3.0
  bounce: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Bold
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
    - family: BoldItalic
      fonts:
        - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
    - family: ExtraBold
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
    - family: ExtraBoldItalic
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraBoldItalic.ttf
    - family: ExtraLight
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
    - family: ExtraLightItalic
      fonts:
        - asset: assets/fonts/PlusJakartaSans-ExtraLightItalic.ttf
    - family: Italic
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
    - family: Light
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
    - family: LightItalic
      fonts:
        - asset: assets/fonts/PlusJakartaSans-LightItalic.ttf
    - family: MediumItalic
      fonts:
        - asset: assets/fonts/PlusJakartaSans-MediumItalic.ttf
    - family: SemiBoldItalic
      fonts:
        - asset: assets/fonts/PlusJakartaSans-SemiBoldItalic.ttf
    - family: Medium
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
    - family: Regular
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
    - family: SemiBold
      fonts:
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
